esphome:
  name: "esphome-web-b11b06"
  friendly_name: RFID Test 2
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
wifi:
  ssid: !secret wifi_ssid_werkstatt
  password: !secret wifi_password_geh_weg

  ap:
    ssid: "RFID Fallback Hotspot"
    password: "ySOviYHNNji7"

# Allow Over-The-Air updates
ota:
- platform: esphome

logger:
  
external_components:
  - source: my_components
    components: [uart_card_reader]

uart:
  id: rfid_uart
  rx_pin: GPIO13
  tx_pin: GPIO12
  baud_rate: 9600

uart_card_reader:
  id: my_reader
  uart_id: rfid_uart
  on_tag:
    then:
      - logger.log:
          format: "Karte erkannt! ID: %u | Typ: %u"
          args: [card_id, card_type]