esphome:
  name: esphome-web-b27b15
  friendly_name: Pellets

esp8266:
  board: d1_mini

# Enable logging
logger:

ota:
  platform: esphome

# Enable Home Assistant API
api:
  encryption:
    key: "CTOQdhZtdv651Gf5YNS1n0ncuOI+7kdgic3UvTkF/RI="

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: Pellets
    filters:
      - delayed_off: 10ms
      - delayed_on: 10ms

wifi:
  networks:
  - ssid: !secret wifi_ssid_geh_weg
    password: !secret wifi_password_geh_weg
  - ssid: !secret wifi_ssid_werkstatt
    password: !secret wifi_password_werkstatt
  - ssid: !secret wifi_ssid_geh_weg2_4
    password: !secret wifi_password_geh_weg2_4
  - ssid: !secret wifi_ssid_werkstatt2_4
    password: !secret wifi_password_werkstatt2_4

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heizung Fallback Hotspot"
    password: "ZL6AaNDAZxTC"

captive_portal:
    

    