esphome:
  name: turtaster
  friendly_name: Türtaster

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MB4bLkNNJ5+mvghC+EClHmUer9dQNd97v/ed/QPfciw="

ota:
  password: "655e5ce3059888cdd55f30c504a4baf7"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid_geh_weg2_4
  password: !secret wifi_password_geh_weg

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Turtaster Fallback Hotspot"
    password: "ySOviYHNNji7"

captive_portal:
    
switch:
  - platform: gpio
    pin: 0
    id: relay
    name: "Gate Remote"
    icon: "mdi:gate"
    inverted: true
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay