esphome:
  name: esphome-web-4805d4
  friendly_name: BLE Wohnzimmer
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid_geh_weg
  password: !secret wifi_password_geh_weg

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Turtaster Fallback Hotspot"
    password: "ySOviYHNNji7"

esp32_ble_tracker:

bluetooth_proxy:

binary_sensor:
  - platform: ble_presence
    mac_address: D4:3A:2C:B5:D0:55
    name: "BLE Tracker Pixel Pro"

sensor:
  - platform: ble_rssi
    mac_address: D4:3A:2C:B5:D0:55
    name: "BLE RSSI Pixel Pro"