esphome:
  name: esphome-web-6a08fc
  friendly_name: RFID Test 2
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
wifi:
  ssid: !secret wifi_ssid_geh_weg2_4
  password: !secret wifi_password_geh_weg

  ap:
    ssid: "RFID Fallback Hotspot"
    password: "ySOviYHNNji7"

# Allow Over-The-Air updates
ota:
- platform: esphome

logger:
  
external_components:
  - source: my_components
    components: [uart_card_reader]

uart:
  rx_pin: D7
  tx_pin: D6
  baud_rate: 9600

uart_card_reader:
  id: my_reader
  on_tag:
    then:
      - logger.log:
          format: "Karte erkannt! ID: %u | Typ: %u"
          args: [card_id, card_type]